export const makeT = (lang) => (key) => {
  const dict = {
    en: {
      startNow: 'Start now',
      vnPassportDesc: 'Renew or replace your Vietnam passport. Fee: $230.',
      brand: 'Ngọc Anh Services',
      barCallZelle: 'Zelle / Call',
      home: 'Home',
      sendMoney: 'Send Money',
      visaServices: 'Visa Services',
      visaServicesVi: 'Dịch Vụ Visa',
      trackFaqs: 'Track / FAQs',
      contact: 'Contact',
      language: 'Language',
      welcome: 'Welcome to Ngọc Anh Services',
      welcomeSub: 'Money transfer, shipping, and travel support',
      contactBlurb: "We’ll review your information and get back to you within 1 business day.",
      completeTime: 'Complete in 5–7 business days',
      visaIntroTitle: 'Visa Exception (5-Year) — Overview',
      visaIntro: 'Giấy miễn thị thực là loại giấy tờ có giá trị nhập cảnh, xuất cảnh Việt Nam được cấp cho người Việt Nam định cư ở nước ngoài hoặc người nước ngoài là vợ, chồng, con của công dân Việt Nam hoặc người Việt Nam định cư ở nước ngoài. Giấy này có giá trị thay thế thị thực Việt Nam để nhập cảnh với mục đích thăm thân, giải quyết việc riêng. Người nhập cảnh Việt Nam bằng Giấy miễn thị thực được tạm trú tại Việt Nam không quá 06 tháng cho mỗi lần nhập cảnh.',
      visaFormTitle: 'Apply for Visa Exception (5 Years)',
      visaType: 'Visa Type',
      visaTypeDefault: 'Visa Exception, 5 Years',
      fullName: 'Full Name',
      dob: 'Date of Birth',
      nationality: 'Nationality',
      issuingCountry: 'Issuing Country',
      defaultIssuingCountry: 'United States',
      passportNumber: 'Passport Number',
      submit: 'Submit',
      thanks: 'Thank you! We will contact you soon.',
      examplePassportScan: 'Example of valid passport scan',
      examplePassportPhoto: 'Example of valid passport-style photo',
      privacyTitle: 'Privacy Policy',
      privacyIntro: 'Ngoc Anh Services (“we,” “our,” or “us”) values your trust and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, and protect your information when you use our website and services.',
      privacySection1: '1. Information We Collect',
      privacySection1a: 'Personal details you provide (name, date of birth, nationality, etc.).',
      privacySection1b: 'Uploaded documents (passport scans, ID cards, photos, etc.).',
      privacySection1c: 'Contact information (email, phone, address).',
      privacySection2: '2. How We Use Information',
      privacySection2intro: 'We use your information strictly for:',
      privacySection2a: 'Processing visa services and travel-related requests.',
      privacySection2b: 'Communicating with you about your application.',
      privacySection2c: 'Complying with legal and regulatory requirements.',
      privacySection3: '3. File Storage',
      privacySection3text: 'Uploaded files are securely stored and used only for processing your request. We do not share your documents with third parties except as required by law or with government/immigration authorities when necessary.',
      privacySection4: '4. Data Protection',
      privacySection4text: 'We implement technical and organizational measures to protect your information from unauthorized access, loss, or misuse.',
      privacySection5: '5. Your Rights',
      privacySection5text: 'You may request access, correction, or deletion of your personal information by contacting us.',
      privacySection6: '6. Contact Us',
      privacySection6text: 'If you have any questions about this Privacy Policy, please contact us at:',
      privacyUpdated: 'Last updated',
      privacyPolicy: 'Privacy Policy',
      consentText: 'I consent to upload and storage of my personal documents for visa processing. By continuing, I agree to the <a href="#" data-privacy-link class="text-emerald-600 underline">Privacy Policy</a>.',

      vnPassport: 'VN Passport',
      selectSex: 'Select sex…',
      fullName: 'Full Name',
      dob: 'Date of Birth',
      sex: 'Sex',
      pob: 'Place of Birth',
      phone: 'Phone Number',
      addressUS: 'Address in US',
      addressVN: 'Address in Vietnam',
      occupation: 'Occupation',
      workInfo: 'Work Name and Address',
      fatherName: 'Father Name',
      fatherDob: 'Father Date of Birth',
      motherName: 'Mother Name',
      motherDob: 'Mother Date of Birth',
      spouseName: 'Spouse Name (optional)',
      spouseDob: 'Spouse Date of Birth (optional)',
      departDate: 'Date Depart Vietnam',
      airport: 'Airport',
      usIdFile: 'US Passport or Green Card',
      oldVnPassFile: 'Old Vietnam Passport',
      photoFile: 'Passport Style Photo',
      email: 'Customer Email (for confirmation copy)',
    },
    vi: {
      startNow: 'Bắt đầu',
      vnPassportDesc: 'Gia hạn hoặc đổi hộ chiếu Việt Nam. Phí: $230.',
      brand: 'Ngọc Anh Services',
      barCallZelle: 'Zelle / Gọi',
      home: 'Trang chủ',
      sendMoney: 'Gửi tiền',
      visaServices: 'Visa Services',
      visaServicesVi: 'Dịch Vụ Visa',
      trackFaqs: 'Theo dõi / Hỏi đáp',
      contact: 'Liên hệ',
      language: 'Ngôn ngữ',
      welcome: 'Chào mừng đến Ngọc Anh Services',
      welcomeSub: 'Dịch vụ chuyển tiền, gửi hàng, và hỗ trợ du lịch',
      contactBlurb: "Chúng tôi sẽ xem xét thông tin của bạn và liên hệ với bạn về các bước tiếp theo và hồ sơ cần thiết",
      completeTime: 'Hoàn tất trong 5–7 ngày làm việc',
      visaIntroTitle: 'Miễn Thị Thực 5 Năm — Tổng quan',
      visaIntro: 'Giấy miễn thị thực là loại giấy tờ có giá trị nhập cảnh, xuất cảnh Việt Nam được cấp cho người Việt Nam định cư ở nước ngoài hoặc người nước ngoài là vợ, chồng, con của công dân Việt Nam hoặc người Việt Nam định cư ở nước ngoài. Giấy này có giá trị thay thế thị thực Việt Nam để nhập cảnh với mục đích thăm thân, giải quyết việc riêng. Người nhập cảnh Việt Nam bằng Giấy miễn thị thực được tạm trú tại Việt Nam không quá 06 tháng cho mỗi lần nhập cảnh.',
      visaFormTitle: 'Đăng ký Miễn Thị Thực 5 Năm',
      visaType: 'Loại Visa',
      visaTypeDefault: 'Miễn thị thực 5 năm',
      fullName: 'Họ và Tên',
      dob: 'Ngày sinh',
      nationality: 'Quốc tịch',
      issuingCountry: 'Nước cấp',
      defaultIssuingCountry: 'Hoa Kỳ',
      passportNumber: 'Số hộ chiếu',
      submit: 'Gửi',
      thanks: 'Cảm ơn! Chúng tôi sẽ liên hệ sớm.',
      examplePassportScan: 'Ví dụ scan hộ chiếu hợp lệ',
      examplePassportPhoto: 'Ví dụ ảnh thẻ đúng chuẩn',
      privacyTitle: 'Chính Sách Bảo Mật',
      privacyIntro: 'Ngọc Anh Services (“chúng tôi”) trân trọng sự tin tưởng của bạn và cam kết bảo vệ thông tin cá nhân của bạn. Chính sách này giải thích cách chúng tôi thu thập, sử dụng và bảo vệ thông tin khi bạn sử dụng website và dịch vụ của chúng tôi.',
      privacySection1: '1. Thông Tin Chúng Tôi Thu Thập',
      privacySection1a: 'Thông tin cá nhân bạn cung cấp (họ tên, ngày sinh, quốc tịch, v.v.).',
      privacySection1b: 'Tài liệu đã tải lên (hộ chiếu, CMND/CCCD, ảnh, v.v.).',
      privacySection1c: 'Thông tin liên hệ (email, số điện thoại, địa chỉ).',
      privacySection2: '2. Cách Chúng Tôi Sử Dụng Thông Tin',
      privacySection2intro: 'Chúng tôi chỉ sử dụng thông tin của bạn cho:',
      privacySection2a: 'Xử lý dịch vụ visa và yêu cầu liên quan đến du lịch.',
      privacySection2b: 'Liên hệ với bạn về hồ sơ đã nộp.',
      privacySection2c: 'Tuân thủ yêu cầu pháp luật và cơ quan quản lý.',
      privacySection3: '3. Lưu Trữ Tài Liệu',
      privacySection3text: 'Các tệp đã tải lên được lưu trữ an toàn và chỉ dùng cho việc xử lý hồ sơ của bạn. Chúng tôi không chia sẻ tài liệu của bạn với bên thứ ba, trừ khi theo yêu cầu pháp luật hoặc cần thiết cho cơ quan xuất nhập cảnh.',
      privacySection4: '4. Bảo Vệ Dữ Liệu',
      privacySection4text: 'Chúng tôi áp dụng các biện pháp kỹ thuật và tổ chức để bảo vệ thông tin của bạn khỏi truy cập trái phép, mất mát hoặc lạm dụng.',
      privacySection5: '5. Quyền Lợi Của Bạn',
      privacySection5text: 'Bạn có thể yêu cầu truy cập, chỉnh sửa hoặc xóa thông tin cá nhân của mình bằng cách liên hệ với chúng tôi.',
      privacySection6: '6. Liên Hệ',
      privacySection6text: 'Nếu bạn có bất kỳ câu hỏi nào về Chính Sách Bảo Mật, vui lòng liên hệ qua:',
      privacyUpdated: 'Cập nhật lần cuối',
      privacyPolicy: 'Chính Sách Bảo Mật',
      consentText: 'Tôi đồng ý tải lên và lưu trữ các tài liệu cá nhân của mình để xử lý thị thực. Khi tiếp tục, tôi đồng ý với <a href="#" data-privacy-link class="text-emerald-600 underline">Chính Sách Bảo Mật</a>.',

      vnPassport: 'Hộ chiếu VN',
      selectSex: 'Chọn giới tính…',
      fullName: 'Họ và Tên',
      dob: 'Ngày Sinh',
      sex: 'Giới Tính',
      pob: 'Nơi Sinh',
      phone: 'Số Điện Thoại',
      addressUS: 'Địa chỉ tại Mỹ',
      addressVN: 'Địa chỉ tại Việt Nam',
      occupation: 'Nghề nghiệp',
      workInfo: 'Tên & Địa chỉ Nơi làm việc',
      fatherName: 'Tên Cha',
      fatherDob: 'Ngày sinh của Cha',
      motherName: 'Tên Mẹ',
      motherDob: 'Ngày sinh của Mẹ',
      spouseName: 'Tên Vợ/Chồng (không bắt buộc)',
      spouseDob: 'Ngày sinh của Vợ/Chồng (không bắt buộc)',
      departDate: 'Ngày Rời Việt Nam',
      airport: 'Sân bay',
      usIdFile: 'Hộ chiếu Mỹ hoặc Thẻ Xanh',
      oldVnPassFile: 'Hộ chiếu Việt Nam cũ',
      photoFile: 'Ảnh thẻ hộ chiếu',
      email: 'Email khách hàng (nhận bản sao)',
    }
  }
  return dict[lang]?.[key] ?? key
}
